# Generated by Django 5.2.1 on 2025-05-12 00:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, default='images/cover/coverphoto.jpg', null=True, upload_to=accounts.models.cover_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_path),
        ),
    ]
