# Generated by Django 5.2.1 on 2025-05-12 01:15

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_cover_pic_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.MediaStorage()),
        ),
    ]
